# _config.yml

# Site settings
title: My Jekyll Site
description: A description of your site
baseurl: "" # Set the base URL if your site is not hosted at the root domain

# Build settings
markdown: kramdown # Set the Markdown processor
theme: my-theme # Set the name of your Jekyll theme

# Plugin settings (if needed)
plugins:
  - jekyll-feed
  - jekyll-sitemap
